#!/bin/bash
set -euo pipefail

# Force fix env_config.dart to resolve $BRANCH compilation error
# This script completely replaces the file with correct static content

log() { echo "[$(date +'%Y-%m-%d %H:%M:%S')] [FORCE_FIX] $1"; }

# Source environment configuration
SCRIPT_DIR="$(dirname "$0")"
if [ -f "${SCRIPT_DIR}/../config/env.sh" ]; then
    source "${SCRIPT_DIR}/../config/env.sh"
    log "Environment configuration loaded from lib/config/env.sh"
elif [ -f "${SCRIPT_DIR}/../../lib/config/env.sh" ]; then
    source "${SCRIPT_DIR}/../../lib/config/env.sh"
    log "Environment configuration loaded from lib/config/env.sh"
else
    log "Environment configuration file not found, using system environment variables"
fi

log "🚨 FORCE FIXING env_config.dart to resolve \$BRANCH compilation error"

# Create the directory if it doesn't exist
mkdir -p lib/config

# Backup any existing file
if [ -f "lib/config/env_config.dart" ]; then
    cp lib/config/env_config.dart lib/config/env_config.dart.broken 2>/dev/null || true
    log "📋 Backed up potentially broken file to env_config.dart.broken"
fi

# Force write the correct file content (no variable substitution)
cat > lib/config/env_config.dart << 'EOF'
// 🔥 GENERATED FILE: DO NOT EDIT 🔥
//
// This file is generated by lib/scripts/utils/gen_env_config.sh
// It contains all environment-specific variables for the app.

class EnvConfig {
  // App Metadata
  static const String appId = "";
  static const String versionName = "1.0.0";
  static const int versionCode = 1;
  static const String appName = "QuikApp";
  static const String orgName = "";
  static const String webUrl = "";
  static const String userName = "";
  static const String emailId = "";
  static const String branch = "main";
  static const String workflowId = "";

  // Package Identifiers
  static const String pkgName = "";
  static const String bundleId = "";

  // Feature Flags (converted to bool)
  static const bool pushNotify = false;
  static const bool isChatbot = false;
  static const bool isDomainUrl = false;
  static const bool isSplash = true;
  static const bool isPulldown = true;
  static const bool isBottommenu = true;
  static const bool isLoadIndicator = true;

  // Permissions (converted to bool)
  static const bool isCamera = false;
  static const bool isLocation = false;
  static const bool isMic = false;
  static const bool isNotification = false;
  static const bool isContact = false;
  static const bool isBiometric = false;
  static const bool isCalendar = false;
  static const bool isStorage = false;

  // UI/Branding
  static const String logoUrl = "";
  static const String splashUrl = "";
  static const String splashBg = "";
  static const String splashBgColor = "#FFFFFF";
  static const String splashTagline = "";
  static const String splashTaglineColor = "#000000";
  static const String splashAnimation = "none";
  static const int splashDuration = 3;

  // Bottom Menu Configuration
  static const String bottommenuItems = r'[]';
  static const String bottommenuBgColor = "#FFFFFF";
  static const String bottommenuIconColor = "#000000";
  static const String bottommenuTextColor = "#000000";
  static const String bottommenuFont = "DM Sans";
  static const double bottommenuFontSize = 14.0;
  static const bool bottommenuFontBold = false;
  static const bool bottommenuFontItalic = false;
  static const String bottommenuActiveTabColor = "#0000FF";
  static const String bottommenuIconPosition = "top";
  static const String bottommenuVisibleOn = "";

  // Firebase Configuration
  static const String firebaseConfigAndroid = "";
  static const String firebaseConfigIos = "";

  // Android Signing
  static const String keyStoreUrl = "";
  static const String cmKeystorePassword = "";
  static const String cmKeyAlias = "";
  static const String cmKeyPassword = "";

  // iOS Signing
  static const String appleTeamId = "";
  static const String apnsKeyId = "";
  static const String apnsAuthKeyUrl = "";
  static const String certPassword = "";
  static const String profileUrl = "";
  static const String certP12Url = "";
  static const String certCerUrl = "";
  static const String certKeyUrl = "";
  static const String profileType = "app-store";
  static const String appStoreConnectKeyIdentifier = "";

  // Build Environment
  static const String buildId = "unknown";
  static const String buildDir = "";
  static const String projectRoot = "";
  static const String outputDir = "output";

  // Utility Methods
  static bool get isAndroidBuild => workflowId.startsWith('android');
  static bool get isIosBuild => workflowId.contains('ios');
  static bool get isCombinedBuild => workflowId == 'combined';
  static bool get hasFirebase => firebaseConfigAndroid.isNotEmpty || firebaseConfigIos.isNotEmpty;
  static bool get hasKeystore => keyStoreUrl.isNotEmpty;
  static bool get hasIosSigning => certPassword.isNotEmpty && profileUrl.isNotEmpty;
}
EOF

# Verify the fix worked
if grep -q '\$BRANCH' lib/config/env_config.dart; then
    log "❌ CRITICAL FAILURE: File still contains \$BRANCH after force fix"
    exit 1
else
    log "✅ SUCCESS: File no longer contains \$BRANCH pattern"
fi

# Show verification
log "🔍 Verification - branch line content:"
grep -n "branch" lib/config/env_config.dart || true

log "🎉 Force fix completed successfully - env_config.dart is now safe for compilation" 