// 🔥 GENERATED FILE: DO NOT EDIT 🔥
//
// This file is generated by lib/scripts/utils/gen_env_config.sh
// It contains all environment-specific variables for the app.

class EnvConfig {
  // App Metadata
  static const String appId = "";
  static const String versionName = "1.0.0";
  static const int versionCode = 1;
  static const String appName = "QuikApp";
  static const String orgName = "";
  static const String webUrl = "";
  static const String userName = "";
  static const String emailId = "";
  static const String branch = "main";
  static const String workflowId = "";

  // Package Identifiers
  static const String pkgName = "";
  static const String bundleId = "";

  // Feature Flags (converted to bool)
  static const bool pushNotify = false;
  static const bool isChatbot = false;
  static const bool isDomainUrl = false;
  static const bool isSplash = true;
  static const bool isPulldown = true;
  static const bool isBottommenu = true;
  static const bool isLoadIndicator = true;

  // Permissions (converted to bool)
  static const bool isCamera = false;
  static const bool isLocation = false;
  static const bool isMic = false;
  static const bool isNotification = false;
  static const bool isContact = false;
  static const bool isBiometric = false;
  static const bool isCalendar = false;
  static const bool isStorage = false;

  // UI/Branding
  static const String logoUrl = "";
  static const String splashUrl = "";
  static const String splashBg = "";
  static const String splashBgColor = "#FFFFFF";
  static const String splashTagline = "";
  static const String splashTaglineColor = "#000000";
  static const String splashAnimation = "none";
  static const int splashDuration = 3;

  // Bottom Menu Configuration
  static const String bottommenuItems = """[]""";
  static const String bottommenuBgColor = "#FFFFFF";
  static const String bottommenuIconColor = "#000000";
  static const String bottommenuTextColor = "#000000";
  static const String bottommenuFont = "DM Sans";
  static const double bottommenuFontSize = 14.0;
  static const bool bottommenuFontBold = false;
  static const bool bottommenuFontItalic = false;
  static const String bottommenuActiveTabColor = "#0000FF";
  static const String bottommenuIconPosition = "top";
  static const String bottommenuVisibleOn = "";

  // Firebase Configuration
  static const String firebaseConfigAndroid = "";
  static const String firebaseConfigIos = "";

  // Android Signing
  static const String keyStoreUrl = "";
  static const String cmKeystorePassword = "";
  static const String cmKeyAlias = "";
  static const String cmKeyPassword = "";

  // iOS Signing
  static const String appleTeamId = "";
  static const String apnsKeyId = "";
  static const String apnsAuthKeyUrl = "";
  static const String certPassword = "";
  static const String profileUrl = "";
  static const String certP12Url = "";
  static const String certCerUrl = "";
  static const String certKeyUrl = "";
  static const String profileType = "app-store";
  static const String appStoreConnectKeyIdentifier = "";

  // Build Environment
  static const String buildId = "unknown";
  static const String buildDir = "";
  static const String projectRoot = "";
  static const String outputDir = "output";

  // Utility Methods
  static bool get isAndroidBuild => workflowId.startsWith('android');
  static bool get isIosBuild => workflowId.contains('ios');
  static bool get isCombinedBuild => workflowId == 'combined';
  static bool get hasFirebase => firebaseConfigAndroid.isNotEmpty || firebaseConfigIos.isNotEmpty;
  static bool get hasKeystore => keyStoreUrl.isNotEmpty;
  static bool get hasIosSigning => certPassword.isNotEmpty && profileUrl.isNotEmpty;
}
