#!/usr/bin/env bash

# Simple iOS Workflow Script - Core functionality only
set -e

echo "🔍 Starting Simple iOS Workflow"

# Function to safely get environment variable
safe_env_var() {
    local var_name="$1"
    local fallback="$2"
    local value="${!var_name:-}"
    
    if [ "$value" = "\$$var_name" ] || [ "$value" = "$var_name" ] || [ -z "$value" ] || [[ "$value" == *"\$$var_name"* ]]; then
        echo "$fallback"
    else
        echo "$value" | tr -d '\r\n\t' | sed 's/[^[:print:]]//g'
    fi
}

# Function to clean environment variables
clean_env_var() {
    local value="$1"
    echo "$value" | tr -d '\r\n\t' | sed 's/[^[:print:]]//g'
}

echo "🔍 Generating env_config.dart..."

# Create config directory
mkdir -p lib/config

# Generate the env_config.dart file
cat > lib/config/env_config.dart << 'EOF'
// Generated by Simple iOS Workflow Script
// Do not edit manually

class EnvConfig {
  // App Information
  static const String appName = "";
  static const String webUrl = "";

  // Feature Flags
  static const bool pushNotify = false;
  static const bool isChatbot = false;
  static const bool isDomainUrl = false;
  static const bool isSplash = true;
  static const bool isPulldown = false;
  static const bool isBottommenu = false;
  static const bool isLoadIndicator = false;

  // Permissions
  static const bool isCamera = false;
  static const bool isLocation = false;
  static const bool isMic = false;
  static const bool isNotification = false;
  static const bool isContact = false;
  static const bool isBiometric = false;
  static const bool isCalendar = false;

  // UI Configuration
  static const String splashBgColor = "#FFFFFF";
  static const String splashTagline = "";
  static const String splashTaglineColor = "#000000";
  static const String splashAnimation = "fade";
  static const int splashDuration = 3;
  static const String splashUrl = "";
  static const String splashBg = "";

  // Bottom Menu Configuration
  static const String bottommenuItems = "[]";
  static const String bottommenuBgColor = "#FFFFFF";
  static const String bottommenuActiveTabColor = "#007AFF";
  static const String bottommenuTextColor = "#666666";
  static const String bottommenuIconColor = "#666666";
  static const String bottommenuIconPosition = "above";
  static const String bottommenuFont = "Roboto";
  static const double bottommenuFontSize = 12;
  static const bool bottommenuFontBold = false;
  static const bool bottommenuFontItalic = false;

  // Firebase Configuration
  static const String firebaseConfigAndroid = "";
  static const String firebaseConfigIos = "";
}
EOF

echo "✅ env_config.dart generated successfully"

# Validate the generated file
echo "🔍 Validating generated env_config.dart..."
if dart analyze lib/config/env_config.dart > /dev/null 2>&1; then
    echo "✅ env_config.dart is syntactically correct"
else
    echo "❌ env_config.dart has syntax errors"
    dart analyze lib/config/env_config.dart
    exit 1
fi

echo "✅ Simple iOS Workflow completed successfully" 