// Generated by Simple Robust iOS Workflow Script
// Do not edit manually

class EnvConfig {
  // App Information
  static const String appName = "Test App";
  static const String versionName = "1.0.0";
  static const String versionCode = "1";
  static const String bundleId = "com.test.app";
  static const String packageName = "com.test.app";
  static const String organizationName = "Test Organization";
  static const String webUrl = "https://test.com";
  static const String userName = "testuser";
  static const String appId = "12345";
  static const String workflowId = "ios-workflow";

  // Feature Flags
  static const bool pushNotify = true;
  static const bool isChatbot = true;
  static const bool isDomainUrl = true;
  static const bool isSplash = true;
  static const bool isPulldown = true;
  static const bool isBottommenu = true;
  static const bool isLoadIndicator = true;

  // Permissions
  static const bool isCamera = false;
  static const bool isLocation = false;
  static const bool isMic = true;
  static const bool isNotification = true;
  static const bool isContact = false;
  static const bool isBiometric = false;
  static const bool isCalendar = false;
  static const bool isStorage = true;

  // UI Configuration
  static const String splashBgColor = "#cbdbf5";
  static const String splashTagline = "TEST APP";
  static const String splashTaglineColor = "#a30237";
  static const String splashAnimation = "zoom";
  static const int splashDuration = 4;
  static const String splashUrl = "https://example.com/splash.png";
  static const String splashBg = "https://example.com/splash_bg.png";

  // Bottom Menu Configuration
  static const String bottomMenuItems = "[{\"label\":\"Home\",\"icon\":{\"type\":\"preset\",\"name\":\"home_outlined\"},\"url\":\"https://example.com/\"}]";
  static const String bottomMenuBgColor = "#FFFFFF";
  static const String bottomMenuIconColor = "#6d6e8c";
  static const String bottomMenuTextColor = "#6d6e8c";
  static const String bottomMenuFont = "DM Sans";
  static const String bottomMenuFontSize = "12";
  static const bool bottomMenuFontBold = false;
  static const bool bottomMenuFontItalic = false;
  static const String bottomMenuActiveTabColor = "#a30237";
  static const String bottomMenuIconPosition = "above";
  static const String bottommenuItems = "[{\"label\":\"Home\",\"icon\":{\"type\":\"preset\",\"name\":\"home_outlined\"},\"url\":\"https://example.com/\"}]";
  static const String bottommenuBgColor = "#FFFFFF";
  static const String bottommenuActiveTabColor = "#a30237";
  static const String bottommenuTextColor = "#6d6e8c";
  static const String bottommenuIconColor = "#6d6e8c";
  static const String bottommenuIconPosition = "above";
  static const String bottommenuFont = "DM Sans";
  static const double bottommenuFontSize = 12;
  static const bool bottommenuFontBold = false;
  static const bool bottommenuFontItalic = false;
  static const String firebaseConfigAndroid = "";
  static const String firebaseConfigIos = "";
}
