// Generated by Test Dart Syntax Fix Script
// Do not edit manually

class EnvConfig {
  // App Information
  static const String appName = "Test App";
  static const String versionName = "1.0.0";
  static const String versionCode = "1";
  static const String bundleId = "com.test.app";

  // Feature Flags
  static const bool isPushNotify = true;
  static const bool isChatbot = true;
  static const bool isSplash = true;

  // Permissions
  static const bool isCamera = false;
  static const bool isMic = true;
  static const bool isNotification = true;
  static const bool isStorage = true;

  // UI Configuration
  static const String splashBgColor = "#cbdbf5";
  static const String splashTagline = "TEST APP";
  static const String splashTaglineColor = "#a30237";
  static const String splashAnimation = "zoom";
  static const String splashDuration = "4";

  // Bottom Menu Configuration
  static const String bottomMenuItems = "[{\"label\":\"Home\",\"icon\":{\"type\":\"preset\",\"name\":\"home_outlined\"},\"url\":\"https://example.com/\"},{\"label\":\"About\",\"icon\":{\"type\":\"custom\",\"icon_url\":\"https://example.com/about.svg\",\"icon_size\":\"24\"},\"url\":\"https://example.com/about\"}]";
  static const String bottomMenuBgColor = "#FFFFFF";
  static const String bottomMenuIconColor = "#6d6e8c";
  static const String bottomMenuTextColor = "#6d6e8c";
  static const String bottomMenuFont = "DM Sans";
  static const String bottomMenuFontSize = "12";
  static const bool bottomMenuFontBold = false;
  static const bool bottomMenuFontItalic = false;
  static const String bottomMenuActiveTabColor = "#a30237";
  static const String bottomMenuIconPosition = "above";
}
