// Generated by Enhanced iOS Workflow with Certificate Generation
// Do not edit manually

class EnvConfig {
  // App Information
  static const String appName = '[2025-07-25 16:00:24] [ENHANCED_IOS] ✅ Found APP_NAME: Test App
Test App';
  static const String versionName = '[2025-07-25 16:00:24] [ENHANCED_IOS] ✅ Found VERSION_NAME: 1.0.0
1.0.0';
  static const String versionCode = '[2025-07-25 16:00:24] [ENHANCED_IOS] ✅ Found VERSION_CODE: 1
1';
  static const String bundleId = '[2025-07-25 16:00:24] [ENHANCED_IOS] ✅ Found BUNDLE_ID: com.garbcode.garbcodeapp
com.garbcode.garbcodeapp';
  static const String packageName = '[2025-07-25 16:00:24] [ENHANCED_IOS] ⚠️ PKG_NAME not set, using fallback: com.garbcode.garbcodeapp
com.garbcode.garbcodeapp';
  static const String organizationName = '[2025-07-25 16:00:24] [ENHANCED_IOS] ⚠️ ORG_NAME not set, using fallback: Garbcode Apparels Private Limited
Garbcode Apparels Private Limited';
  static const String webUrl = '[2025-07-25 16:00:24] [ENHANCED_IOS] ⚠️ WEB_URL not set, using fallback: https://garbcode.com/
https://garbcode.com/';
  static const String userName = '[2025-07-25 16:00:24] [ENHANCED_IOS] ⚠️ USER_NAME not set, using fallback: prasannasrie
prasannasrie';
  static const String appId = '[2025-07-25 16:00:24] [ENHANCED_IOS] ⚠️ APP_ID not set, using fallback: 10023
10023';
  static const String workflowId = '[2025-07-25 16:00:24] [ENHANCED_IOS] ⚠️ WORKFLOW_ID not set, using fallback: ios-workflow
ios-workflow';

  // Feature Flags
  static const bool isPushNotify = [2025-07-25 16:00:24] [ENHANCED_IOS] ✅ Found PUSH_NOTIFY: false
false;
  static const bool isChatbot = [2025-07-25 16:00:24] [ENHANCED_IOS] ⚠️ IS_CHATBOT not set, using fallback: true
true;
  static const bool isDomainUrl = [2025-07-25 16:00:24] [ENHANCED_IOS] ⚠️ IS_DOMAIN_URL not set, using fallback: true
true;
  static const bool isSplash = [2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ IS_SPLASH not set, using fallback: true
true;
  static const bool isPulldown = [2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ IS_PULLDOWN not set, using fallback: true
true;
  static const bool isBottomMenu = [2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ IS_BOTTOMMENU not set, using fallback: true
true;
  static const bool isLoadInd = [2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ IS_LOAD_IND not set, using fallback: true
true;

  // Permissions
  static const bool isCamera = [2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ IS_CAMERA not set, using fallback: false
false;
  static const bool isLocation = [2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ IS_LOCATION not set, using fallback: false
false;
  static const bool isMic = [2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ IS_MIC not set, using fallback: true
true;
  static const bool isNotification = [2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ IS_NOTIFICATION not set, using fallback: true
true;
  static const bool isContact = [2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ IS_CONTACT not set, using fallback: false
false;
  static const bool isBiometric = [2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ IS_BIOMETRIC not set, using fallback: false
false;
  static const bool isCalendar = [2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ IS_CALENDAR not set, using fallback: false
false;
  static const bool isStorage = [2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ IS_STORAGE not set, using fallback: true
true;

  // Assets
  static const String logoUrl = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ LOGO_URL not set, using fallback: ';
  static const String splashUrl = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ SPLASH_URL not set, using fallback: ';
  static const String splashBgUrl = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ SPLASH_BG_URL not set, using fallback: ';
  static const String splashBgColor = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ SPLASH_BG_COLOR not set, using fallback: #cbdbf5
#cbdbf5';
  static const String splashTagline = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ SPLASH_TAGLINE not set, using fallback: TWINKLUB\nTWINKLUB';
  static const String splashTaglineColor = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ SPLASH_TAGLINE_COLOR not set, using fallback: #a30237
#a30237';
  static const String splashAnimation = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ SPLASH_ANIMATION not set, using fallback: zoom
zoom';
  static const String splashDuration = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ SPLASH_DURATION not set, using fallback: 4
4';

  // Bottom Menu
  static const String bottomMenuItems = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ BOTTOMMENU_ITEMS not set, using fallback: []\n[]';
  static const String bottomMenuBgColor = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ BOTTOMMENU_BG_COLOR not set, using fallback: #FFFFFF
#FFFFFF';
  static const String bottomMenuIconColor = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ BOTTOMMENU_ICON_COLOR not set, using fallback: #6d6e8c
#6d6e8c';
  static const String bottomMenuTextColor = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ BOTTOMMENU_TEXT_COLOR not set, using fallback: #6d6e8c
#6d6e8c';
  static const String bottomMenuFont = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ BOTTOMMENU_FONT not set, using fallback: DM Sans
DM Sans';
  static const String bottomMenuFontSize = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ BOTTOMMENU_FONT_SIZE not set, using fallback: 12
12';
  static const bool bottomMenuFontBold = [2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ BOTTOMMENU_FONT_BOLD not set, using fallback: false
false;
  static const bool bottomMenuFontItalic = [2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ BOTTOMMENU_FONT_ITALIC not set, using fallback: false
false;
  static const String bottomMenuActiveTabColor = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ BOTTOMMENU_ACTIVE_TAB_COLOR not set, using fallback: #a30237
#a30237';
  static const String bottomMenuIconPosition = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ BOTTOMMENU_ICON_POSITION not set, using fallback: above
above';

  // Firebase Configuration
  static const String firebaseConfigIos = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ FIREBASE_CONFIG_IOS not set, using fallback: ';
  static const String apnsKeyId = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ APNS_KEY_ID not set, using fallback: ';
  static const String apnsAuthKeyUrl = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ APNS_AUTH_KEY_URL not set, using fallback: ';

  // Certificate Configuration
  static const String certPassword = '[2025-07-25 16:00:25] [ENHANCED_IOS] ✅ Found CERT_PASSWORD: quikapp2025
quikapp2025';
  static const String certP12Url = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ CERT_P12_URL not set, using fallback: ';
  static const String certCerUrl = '[2025-07-25 16:00:25] [ENHANCED_IOS] ✅ Found CERT_CER_URL: https://raw.githubusercontent.com/prasanna91/QuikApp/main/ios_distribution_gps.cer
https://raw.githubusercontent.com/prasanna91/QuikApp/main/ios_distribution_gps.cer';
  static const String certKeyUrl = '[2025-07-25 16:00:25] [ENHANCED_IOS] ✅ Found CERT_KEY_URL: https://raw.githubusercontent.com/prasanna91/QuikApp/main/private.key
https://raw.githubusercontent.com/prasanna91/QuikApp/main/private.key';

  // Provisioning Profile
  static const String profileType = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ PROFILE_TYPE not set, using fallback: app-store
app-store';
  static const String profileUrl = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ PROFILE_URL not set, using fallback: ';

  // Email Configuration
  static const bool enableEmailNotifications = [2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ ENABLE_EMAIL_NOTIFICATIONS not set, using fallback: true
true;
  static const String emailSmtpServer = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ EMAIL_SMTP_SERVER not set, using fallback: smtp.gmail.com
smtp.gmail.com';
  static const String emailSmtpPort = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ EMAIL_SMTP_PORT not set, using fallback: 587
587';
  static const String emailSmtpUser = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ EMAIL_SMTP_USER not set, using fallback: prasannasrie@gmail.com
prasannasrie@gmail.com';
  static const String emailSmtpPass = '[2025-07-25 16:00:25] [ENHANCED_IOS] ⚠️ EMAIL_SMTP_PASS not set, using fallback: lrnu krfm aarp urux
lrnu krfm aarp urux';
  static const String emailId = '[2025-07-25 16:00:24] [ENHANCED_IOS] ⚠️ EMAIL_ID not set, using fallback: prasannasrinivasan32@gmail.com
prasannasrinivasan32@gmail.com';
}
