// 🔥 GENERATED FILE: DO NOT EDIT 🔥
//
// This file is generated by lib/scripts/utils/gen_env_config.sh
// It contains all environment-specific variables for the app.
// Generated for workflow: unknown

class EnvConfig {
  // App Metadata
  static const String appId = "";
  static const String versionName = "1.0.0";
  static const int versionCode = 1;
  static const String appName = "Garbcode App";
  static const String orgName = "Garbcode";
  static const String webUrl = "https://garbcode.com";
  static const String userName = "Prasanna";
  static const String emailId = "prasannasrinivasan32@gmail.com";
  static const String branch = "main";
  static const String workflowId = "unknown";

  // Package Identifiers
  static const String pkgName = "com.quikapp.app";
  static const String bundleId = "com.example.app";

  // Feature Flags (converted to bool)
  static const bool pushNotify = true;
  static const bool isChatbot = false;
  static const bool isDomainUrl = false;
  static const bool isSplash = true;
  static const bool isPulldown = true;
  static const bool isBottommenu = true;
  static const bool isLoadIndicator = true;

  // Permissions (converted to bool)
  static const bool isCamera = false;
  static const bool isLocation = false;
  static const bool isMic = true;
  static const bool isNotification = true;
  static const bool isContact = false;
  static const bool isBiometric = false;
  static const bool isCalendar = false;
  static const bool isStorage = true;

  // UI/Branding
  static const String logoUrl = "https://raw.githubusercontent.com/prasanna91/QuikApp/main/logo-gc.png";
  static const String splashUrl = "";
  static const String splashBg = "";
  static const String splashBgColor = "#FFFFFF";
  static const String splashTagline = "Welcome to Garbcode";
  static const String splashTaglineColor = "#000000";
  static const String splashAnimation = "fade";
  static const int splashDuration = 3;

  // Bottom Menu Configuration
  static const String bottommenuItems = r'[]';
  static const String bottommenuBgColor = "#FFFFFF";
  static const String bottommenuIconColor = "#000000";
  static const String bottommenuTextColor = "#000000";
  static const String bottommenuFont = "Roboto";
  static const double bottommenuFontSize = 12;
  static const bool bottommenuFontBold = false;
  static const bool bottommenuFontItalic = false;
  static const String bottommenuActiveTabColor = "#0000FF";
  static const String bottommenuIconPosition = "above";
  static const String bottommenuVisibleOn = "all";

  // Firebase Configuration
  static const String firebaseConfigAndroid = "";
  static const String firebaseConfigIos = "";

  // Android Signing
  static const String keyStoreUrl = "";
  static const String cmKeystorePassword = "opeN@1234";
  static const String cmKeyAlias = "my_key_alias";
  static const String cmKeyPassword = "opeN@1234";

  // iOS Signing
  static const String appleTeamId = "";
  static const String apnsKeyId = "V566SWNF69";
  static const String apnsAuthKeyUrl = "https://raw.githubusercontent.com/prasanna91/QuikApp/main/AuthKey_V566SWNF69.p8";
  static const String certPassword = "User@54321";
  static const String profileUrl = "https://raw.githubusercontent.com/prasanna91/QuikApp/main/Garbcode_App_Store.mobileprovision";
  static const String certP12Url = "";
  static const String certCerUrl = "https://raw.githubusercontent.com/prasanna91/QuikApp/main/apple_distribution.cer";
  static const String certKeyUrl = "https://raw.githubusercontent.com/prasanna91/QuikApp/main/privatekey.key";
  static const String profileType = "app-store";
  static const String appStoreConnectKeyIdentifier = "F5229W2Q8S";

  // Build Environment
  static const String buildId = "unknown";
  static const String buildDir = "";
  static const String projectRoot = "";
  static const String outputDir = "output";

  // Utility Methods
  static bool get isAndroidBuild => workflowId.startsWith('android');
  static bool get isIosBuild => workflowId.contains('ios');
  static bool get isCombinedBuild => workflowId == 'combined';
  static bool get hasFirebase => firebaseConfigAndroid.isNotEmpty || firebaseConfigIos.isNotEmpty;
  static bool get hasKeystore => keyStoreUrl.isNotEmpty;
  static bool get hasIosSigning => certPassword.isNotEmpty && profileUrl.isNotEmpty;
}
